Repository kwonsuhyuk/OnAndOff, pull requests merged in 2025-03, with the labels that each got.

#80 [#79] : Header 밑 사이드바 반응형으로 구현 및 서비스 이름 변경 (Favicon 추후 작업예정)
  index.html
  manifest.json
  public/favicon/favicon.ico
  src/Components/common/AppTitle.tsx
  src/Components/common/DarkmodeSwitch.tsx
  src/Components/common/Header.jsx
  src/Components/common/NavTitle.tsx
  src/Components/common/menubar/AdminMenuDesktop.tsx
  src/Components/ui/sidebar.tsx
Labels: refactoring, feat, style

#82 [#81] : MainLayout 지정 및 DarkMode 색상 카드 색상 지정, Header 고정
  src/App.tsx
  src/Components/common/Footer.tsx
  src/Components/common/Header.jsx
  src/Components/company/ ManagerRoutes.tsx
  src/Components/company/ManagerMainContent.tsx
  src/Components/container/ManagerPageContainer.tsx
  src/layout/ManagerLayout.tsx
  tailwind.config.js
Labels: refactoring, feat, style

#83 [#77] : 관리자 페이지 사이드바 리팩토링 및 디자인 수정
  src/App.tsx
  src/Components/common/NavTitle.tsx
  src/Components/common/menubar/AdminMenuDesktop.tsx
  src/Components/common/menubar/AdminMenuMobile.tsx
  src/Components/common/menubar/ManagerMenuBar.tsx
  src/Components/common/menubar/MenuBar.tsx
  src/Components/common/menubar/manager/ManagerMenuBarItem.tsx
  src/Components/common/menubar/manager/ManagerMenuBarList.tsx
  src/Components/company/ ManagerRoutes.tsx
  src/Components/company/ManagerMainContent.tsx
  src/Components/ui/button.tsx
  src/Components/ui/sidebar.tsx
  src/constants/menuConfig.ts
  src/constants/routes.ts
  src/hooks/menu/useMenuBar.ts
  src/hooks/menu/useMenuState.ts
  src/hooks/menu/useWindowWidth.ts
  src/pages/manager/CompanyInfoPage.tsx
  src/pages/manager/HolidayManagePage.tsx
  src/pages/manager/TodayAttenancePage.tsx
  src/util/menuBar.util.ts
Labels: refactoring, style

#85 [#84] : 다크모드일때 색상 지정 tailwindconfig 수정
  src/Components/common/Header.jsx
  src/Components/common/menubar/ManagerMenuBar.tsx
  src/Components/company/ManagerMainContent.tsx
  src/Components/ui/card.tsx
  src/Components/ui/sidebar.tsx
  tailwind.config.js
Labels: style

#89 [#86] 직무, 회사 기본정보, 공휴일 / 야간 에 관한 설정 페이지 ui, api 연동
  package-lock.json
  package.json
  src/Components/common/AppTitle.tsx
  src/Components/common/DarkmodeSwitch.tsx
  src/Components/common/TooltipContainer.tsx
  src/Components/common/modal/ImageModal.tsx
  src/Components/company/ ManagerRoutes.tsx
  src/Components/company/company-settings/CompanySettingTitle.tsx
  src/Components/company/company-settings/basic-setting/CompanyBasicStep.tsx
  src/Components/company/company-settings/basic-setting/CompanyLogoUploader.tsx
  src/Components/company/company-settings/job-setting/CompanyJobListStep.tsx
  src/Components/company/company-settings/job-setting/JobCard.tsx
  src/Components/company/company-settings/job-setting/JobListCard.tsx
  src/Components/company/company-settings/night-holiday-setting/CompanyNightHolidayStep.tsx
  src/Components/company/company-settings/night-holiday-setting/HolidaySettings.tsx
  src/Components/company/company-settings/night-holiday-setting/NightPaySettings.tsx
  src/Components/company/company-settings/night-holiday-setting/PayCheckDaySelect.tsx
  src/Components/company/form/FormInputWithButton.tsx
  src/Components/container/manager/CompanyInfoPageContainer.tsx
  src/Components/ui/button.tsx
  src/Components/ui/form.tsx
  src/Components/ui/input.tsx
  src/Components/ui/scroll-area.tsx
  src/Components/ui/select.tsx
  src/Components/ui/separator.tsx
  src/Components/ui/slider.tsx
  src/Components/ui/switch.tsx
  src/Components/ui/toast.tsx
  src/api/index.ts
  src/hooks/company-settings/useCompanyBasicForm.ts
  src/hooks/company-settings/useCompanyInfoPage.ts
  src/hooks/company-settings/useCompanyJobListForm.ts
  src/hooks/company-settings/useCompanyNightHolidayForm.ts
  src/hooks/company-settings/useCompanySettingForm.ts
  src/hooks/company-settings/useCompanyWorkPlacesListForm.ts
  src/hooks/company-settings/useHolidayNightManagePage.ts
  src/hooks/company-settings/usePositionManagePage.ts
  src/hooks/company-settings/useSubmitCompanyData.ts
  src/index.css
  src/layout/ManagerLayout.tsx
  src/model/schema/managerFirstSchema/managerFirst.schema.ts
  src/model/types/company.type.ts
  src/pages/auth/signupProcessPage/ManagerFirstPage.tsx
  src/pages/manager/CompanyInfoPage.tsx
  src/pages/manager/HolidayManagePage.tsx
  src/pages/manager/HolidayNightManagePage.tsx
  src/pages/manager/PositionManagePage.tsx
Labels: refactoring, feat, style

#96 [#88] : 직원 관리 페이지 코드 리팩토링 및 디자인 수정 작업
  package-lock.json
  package.json
  src/Components/auth/UserInfoTable.tsx
  src/Components/company/EmployeeItem.tsx
  src/Components/company/table/EmployeeFilter.tsx
  src/Components/company/table/EmployeeModifyModal.tsx
  src/Components/container/manager/EmployeeListPageContainer.tsx
  src/Components/ui/data-table.tsx
  src/Components/ui/dropdown-menu.tsx
  src/Components/ui/input.tsx
  src/Components/ui/pagination.tsx
  src/Components/ui/select.tsx
  src/Components/ui/table.tsx
  src/api/index.ts
  src/constants/dummyEmployees.ts
  src/constants/empIoyeeFields.ts
  src/constants/employmentType.ts
  src/constants/payment.ts
  src/hooks/manager/useEmployeeList.ts
  src/hooks/manager/useEmployeeModify.ts
  src/model/types/manager.type.ts
  src/model/types/user.type.ts
  src/pages/manager/EmployeeListPage.tsx
  src/pages/manager/EmployeeManagePage.tsx
  src/store/darkmode.store.ts
Labels: refactoring, style

#98 [#97] : 관리자 회사 근무지 설정 페이지 구현
  src/Components/auth/AuthFooter.tsx
  src/Components/auth/ManagerConfirmation.tsx
  src/Components/common/menubar/ManagerMenuBar.tsx
  src/Components/common/menubar/manager/ManagerMenuBarItem.tsx
  src/Components/common/modal/WorkPlaceModal.tsx
  src/Components/company/company-settings/StepperNavigation.tsx
  src/Components/company/company-settings/workplace-setting/CompanyWorkPlaceStep.tsx
  src/Components/company/company-settings/workplace-setting/WorkPlaceItem.tsx
  src/Components/company/company-settings/workplace-setting/WorkPlaceList.tsx
  src/Components/ui/switch.tsx
  src/api/index.ts
  src/hooks/company-settings/useCompanyWorkPlacesListForm.ts
  src/hooks/company-settings/useWorkplacePage.ts
  src/pages/manager/WorkplaceManagePage.tsx
Labels: refactoring, feat, style

#100 [#99] : 메인페이지, 모달 직종 카테고리 매핑
  package-lock.json
  src/Components/company/table/EmployeeFilter.tsx
  src/Components/company/table/EmployeeModifyModal.tsx
  src/Components/ui/select.tsx
  src/pages/manager/EmployeeListPage.tsx
Labels: hotFix

#103 [#101] : api 파일 정리 , 타입 지정 (테스트 필요함)
  src/Components/common/menubar/ManagerMenuBar.tsx
  src/Components/company/ ManagerRoutes.tsx
  src/Components/employee/CompanyInfoHeader.tsx
  src/Components/employee/qr/QrScan.tsx
  src/api/auth.api.ts
  src/api/auth/index.ts
  src/api/commute.api.ts
  src/api/company.api.ts
  src/api/employee.api.ts
  src/api/index.ts
  src/api/map.api.ts
  src/constants/api.path.ts
  src/hooks/auth/useCompanyStep.ts
  src/hooks/auth/useLogin.ts
  src/hooks/auth/useSettingEmployee.ts
  src/hooks/auth/useSignup.ts
  src/hooks/company-settings/useCompanyInfoPage.ts
  src/hooks/company-settings/useHolidayNightManagePage.ts
  src/hooks/company-settings/usePositionManagePage.ts
  src/hooks/company-settings/useSubmitCompanyData.ts
  src/hooks/company-settings/useWorkPlaceModal.ts
  src/hooks/company-settings/useWorkplacePage.ts
  src/hooks/manager/useEmployeeList.ts
  src/hooks/manager/useEmployeeModify.ts
  src/model/schema/managerFirstSchema/managerFirst.schema.ts
  src/pages/common/MainPage.jsx
  src/pages/manager/ManagerSettingBasicPage.tsx
  src/pages/manager/ManagerSettingPage.tsx
Labels: refactoring

#110 [#107] : 공휴일, 야간 selector default value 안나오는 오류 수정
  src/App.tsx
  src/Components/common/menubar/ManagerMenuBar.tsx
  src/Components/company/company-settings/night-holiday-setting/PayCheckDaySelect.tsx
  src/api/auth.api.ts
  src/api/company.api.ts
  src/api/index.ts
  src/constants/routes.ts
  src/hooks/company-settings/useCompanyNightHolidayForm.ts
  src/hooks/company-settings/useHolidayNightManagePage.ts
  src/model/types/company.type.ts
  src/pages/common/MainPage.jsx
  src/pages/manager/DateCheckPage.tsx
Labels: hotFix

#105 [#102] : 직원 관리 페이지 기능 및 스타일 보완
  src/Components/company/table/EmployeeColumns.tsx
  src/Components/company/table/EmployeeFilter.tsx
  src/Components/company/table/EmployeeModifyModal.tsx
  src/Components/container/manager/EmployeeListPageContainer.tsx
  src/Components/ui/data-table.tsx
  src/api/index.ts
  src/hooks/manager/useEmployeeList.ts
  src/hooks/manager/useEmployeeModify.ts
  src/pages/manager/EmployeeListPage.tsx
Labels: refactoring, hotFix, style

#109 [#108] : storybook 테스트
  src/stories/dataTable.stories.tsx
Labels: etc, style

#113 [#111] : 직원 관리 페이지 추가 UI 개선
  src/Components/company/table/EmployeeColumns.tsx
  src/Components/company/table/EmployeeFilter.tsx
  src/Components/company/table/EmployeeModifyModal.tsx
  src/Components/ui/data-table.tsx
  src/Components/ui/pagination.tsx
  src/api/employee.api.ts
  src/api/index.ts
  src/constants/dummyEmployees.ts
  src/hooks/manager/useEmployeeList.ts
  src/hooks/manager/useEmployeeModify.ts
  src/model/types/company.type.ts
  src/pages/common/MainPage.jsx
  src/pages/manager/EmployeeListPage.tsx
  src/store/company.store.ts
Labels: refactoring, hotFix, style

#116 [#115] : 휴가 등록 모달 컴포넌트 생성
  src/Components/common/menubar/ManagerMenuBar.tsx
  src/Components/common/modal/VacationRegisterModal.tsx
  src/Components/ui/date-range-picker.tsx
  src/api/index.ts
  src/constants/menuConfig.ts
  src/pages/manager/VacationApprovedPage.tsx
  src/pages/manager/VacationDetailPage.tsx
  src/pages/manager/VacationListPage.tsx
  src/pages/manager/VacationRegisterPage.tsx
Labels: feat, style

#124 [#123] : 휴가 요청/등록 타입 지정 (+데이터 구조)
  src/model/types/vacation.type.ts
Labels: refactoring, feat

#128 [#126] : vacation 통계페이지 ui 수정
  src/Components/common/calendar/MonthPicker.tsx
  src/Components/common/modal/FilterModal.tsx
  src/Components/company/vacation/VacationFilter.tsx
  src/Components/company/vacation/VacationPieChart.tsx
  src/Components/company/vacation/VacationStatisticTable.tsx
  src/pages/manager/VacationStatisticDetailPage.tsx
Labels: refactoring, style

#131 [#129] : month picker 차트에 적용 및 직원 검색시 자동완성 기능
  src/Components/common/AutoCompleteInput.tsx
  src/Components/company/vacation/VacationChart.tsx
  src/Components/company/vacation/VacationFilter.tsx
  src/Components/company/vacation/VacationPieChart.tsx
  src/api/vacation.api.ts
  src/pages/manager/VacationStatisticPage.tsx
Labels: refactoring, feat, style

#130 [#127] : 휴가 등록 모달 기능 추가 및 스타일 수정 / 휴가 api 로직 추가
  src/Components/common/modal/VacationDetailModal.tsx
  src/Components/common/modal/VacationRegisterModal.tsx
  src/Components/company/table/VacationColumns.tsx
  src/Components/ui/date-range-picker.tsx
  src/Components/ui/dialog.tsx
  src/api/vacation.api.ts
  src/constants/dummyVacationRequests.ts
  src/constants/vacationSelect.ts
  src/constants/vacationTabs.ts
  src/hooks/manager/useEmployeeSearch.ts
  src/hooks/manager/useVacationRegisterModal.ts
  src/hooks/manager/useVacationRequests.ts
  src/pages/manager/VacationDetailPage.tsx
Labels: feat, style

#134 [#132] : 휴가 통계 페이지 검색 툴 개선, ui 개선 및 리팩토링
  src/Components/common/AutoCompleteInput.tsx
  src/Components/common/calendar/MonthPicker.tsx
  src/Components/common/modal/VacationChartModal.tsx
  src/Components/company/vacation/ VacationSubTitle.tsx
  src/Components/company/vacation/CustomLabel.tsx
  src/Components/company/vacation/VacationChart.tsx
  src/Components/company/vacation/VacationFilter.tsx
  src/Components/company/vacation/VacationPieChart.tsx
  src/Components/company/vacation/VacationStatisticTable.tsx
  src/Components/company/vacation/VacationTooltip.tsx
  src/api/vacation.api.ts
  src/constants/ vacation.ts
  src/constants/api.path.ts
  src/constants/vacationstatisticColumns.ts
  src/hooks/manager/useEmployeeList.ts
  src/hooks/vacation/useVacationChartData.ts
  src/hooks/vacation/useVacationPieChart.ts
  src/hooks/vacation/useVacationStatisticTableData.ts
  src/pages/manager/VacationStatisticPage.tsx
  src/util/vacation.util.ts
Labels: refactoring, feat, style

#135 [#133] : 직원 검색 컴포넌트 변경 및 리팩토링
  src/Components/common/modal/VacationDetailModal.tsx
  src/Components/common/modal/VacationRegisterModal.tsx
  src/Components/company/table/EmployeeModifyModal.tsx
  src/Components/company/table/VacationColumns.tsx
  src/Components/company/table/VacationTabContent.tsx
  src/Components/container/manager/VacationRequestPageContainer.tsx
  src/hooks/manager/useVacationDetailModal.ts
  src/hooks/manager/useVacationRegisterModal.ts
  src/hooks/manager/useVacationRequests.ts
  src/pages/manager/VacationDetailPage.tsx
Labels: refactoring

#140 🐛Fix: 로그아웃 시 에러나는 부분 provider 수정 -> 레이아웃 직원 페이지 다시 잡아야함
  src/Components/common/Header.jsx
  src/Components/common/Header.tsx
  src/Components/common/NavTitle.tsx
  src/Components/common/menubar/EmployeeMenuBar.tsx
  src/Components/common/menubar/ManagerMenuBar.tsx
  src/Components/common/menubar/MenuBar.tsx
  src/Components/common/modal/VacationRegisterModal.tsx
  src/Components/company/ ManagerRoutes.tsx
  src/Components/container/EmployeePageContainer.tsx
  src/Components/employee/EmployeeMainContent.tsx
  src/Components/employee/EmployeeRoutes.tsx
  src/Components/ui/sidebar.tsx
  src/Components/ui/switch.tsx
  src/hooks/menu/useMenuBar.ts
  src/hooks/menu/useMenuItems.ts
  src/layout/EmployeeLayout.tsx
  src/pages/common/CompanyMain.jsx
  src/pages/common/MainPage.tsx
Labels: hotFix
