Repository kwonsuhyuk/OnAndOff, pull requests merged in 2025-02, with the labels that each got.

#12 7/api index
  .prettierrc
  src/Components/Calendar/MyCalendar.jsx
  src/Components/Calendar/MyDatePicker.jsx
  src/Components/Employee.jsx
  src/Components/MenuBar.jsx
  src/Components/QR/QrGenerator.jsx
  src/Components/QR/QrScan.jsx
  src/Components/ShowSalary/ SalaryInfoCard.jsx
  src/Components/ShowSalary/ShowSalary.jsx
  src/Components/modal/ImageModal.jsx
  src/api/index.js
Labels: refactoring

#15 ✨Feat: shadcn, react-hook-form 라이브러리 설치 및 기능 테스트
  components.json
  package-lock.json
  package.json
  src/App.jsx
  src/index.css
  src/lib/utils.ts
  tailwind.config.js
  tsconfig.json
  vite.config.js
Labels: etc

#18 [#17] : api/index.js 파일 .val() .exists() 삭제, ref 잘못되어있는 부분 전부 수정
  src/api/index.js
  tailwind.config.js
  tsconfig.json
Labels: hotFix

#19 [#16] 로그인 페이지 리팩 1) ts 적용 및 api 분리
  src/Page/LoginPage.tsx
  src/api/auth/index.ts
  src/model/index.ts
  tsconfig.json
Labels: refactoring

#20 [#17] : qr-scanner 로 라이브러리 교체
  package-lock.json
  package.json
  src/Components/QR/QrGenerator.jsx
  src/Components/QR/QrScan.tsx
  src/api/index.js
Labels: refactoring, feat, hotFix

#23 ♻️Refactor: 로그인 페이지 react-hook-form 적용
  .prettierrc
  src/Page/LoginPage.tsx
  src/Page/SignupPage.jsx
Labels: refactoring

#26 [#22] : qr 스캔 관련 부분 기능 추가 및 버그 수정
  package-lock.json
  package.json
  src/Components/QR/QrGenerator.jsx
  src/Components/QR/QrGenerator.tsx
  src/Components/QR/QrScan.tsx
  src/Page/CompanyMain.jsx
  src/Page/MainPage.jsx
  src/Page/ManagerSettingBasicPage.jsx
  src/Page/signupProcessPage/ManagerFirstPage.jsx
  src/api/index.js
  src/constant/qr.ts
  src/constant/steps.js
  src/main.jsx
  src/model/index.ts
  src/util/encryptDecrypt.ts
  tsconfig.json
Labels: refactoring, feat, hotFix

#31 [#30] : react 18 로 버전 변경 및 createRoot로 변경, zustand 설치 및 user store구축
  package-lock.json
  package.json
  src/main.jsx
  src/store/user.store.ts
Labels: hotFix

#34 [#24] : SignupPage 설정 -완-
  .prettierrc
  src/Components/QR/QrScan.tsx
  src/Page/SignupPage.jsx
  src/Page/SignupPage.tsx
  src/api/auth/index.ts
  src/api/index.js
  src/model/index.ts
Labels: refactoring

#37 [#35]: Guest 로그인 버튼 생성
  src/Page/LoginPage.tsx
Labels: feat

#39 [#38] : Shadcn 설치 설정
  .eslintrc.cjs
  .firebase/hosting.ZGlzdA.cache
  package-lock.json
  package.json
  src/Components/MainContent.tsx
  src/Components/QR/QrScan.tsx
  src/Components/ui/button.tsx
  src/Page/AccessCameraPage.jsx
  src/Page/CompanyMain.jsx
  src/Page/DateCheckPage.jsx
  src/Page/EmployeeListPage.jsx
  src/Page/MainPage.jsx
  src/Page/ManagerSettingBasicPage.jsx
  src/Page/ManagerSettingPage.jsx
  src/Page/ShowCalendarPage.jsx
  src/Page/signupProcessPage/ManagerFirstPage.jsx
  src/index.css
  vite.config.js
Labels: refactoring, feat

#45 [#44] : company store redux -> zustand 로 변경
  src/App.jsx
  src/Components/MainContent.tsx
  src/Components/MenuBar.jsx
  src/Components/QR/QrGenerator.tsx
  src/Components/QR/QrScan.tsx
  src/Components/common/Header.jsx
  src/Page/AccessCameraPage.jsx
  src/Page/CompanyMain.jsx
  src/Page/DateCheckPage.jsx
  src/Page/LoginPage.tsx
  src/Page/MainPage.jsx
  src/Page/SignupPage.tsx
  src/Page/signupProcessPage/ManagerFirstPage.jsx
  src/api/index.js
  src/model/index.ts
  src/store/company.store.ts
  src/store/companySlice.js
  src/store/index.js
  src/store/user.store.ts
Labels: refactoring, feat

#47 [#43] : qr scan 모달 shadcn 적용
  package-lock.json
  package.json
  src/App.css
  src/Components/QR/QrScan.tsx
  src/Components/ui/button.tsx
  src/Components/ui/dialog.tsx
  src/Page/AccessCameraPage.jsx
  src/index.css
  src/reset.css
  tailwind.config.js
Labels: refactoring, feat

#48 [#41] : 로그인/회원가입 페이지 zod라이브러리 적용 및 스키마 정의, shadcn 라이브러리 적용
  package-lock.json
  package.json
  src/Components/auth/AuthFooter.tsx
  src/Components/auth/AuthHeader.tsx
  src/Components/auth/EmployeeCompanyForm.tsx
  src/Components/auth/LoginForm.tsx
  src/Components/auth/ManagerConfirmation.tsx
  src/Components/auth/PersonalInfoForm.tsx
  src/Components/auth/PositionSelector.tsx
  src/Components/ui/alert.tsx
  src/Components/ui/avatar.tsx
  src/Components/ui/button.tsx
  src/Components/ui/card.tsx
  src/Components/ui/checkbox.tsx
  src/Components/ui/form.tsx
  src/Components/ui/input.tsx
  src/Components/ui/label.tsx
  src/Components/ui/radio-group.tsx
  src/Components/ui/separator.tsx
  src/Page/LoginPage.tsx
  src/Page/SignupPage.tsx
  src/api/auth/index.ts
  src/model/index.ts
Labels: refactoring, style

#49 [#22] : qr페이지 및 관련 컴포넌트 refactoring
  src/Components/MainContent.tsx
  src/Components/QR/QrGenerator.tsx
  src/Components/QR/QrScan.tsx
  src/Components/employee/CompanyInfoHeader.tsx
  src/Components/modal/OutWorkingModal.tsx
  src/Page/AccessCameraPage.jsx
  src/Page/signupProcessPage/ManagerFirstPage.jsx
  src/constant/qr.ts
  src/hooks/useWorkingModal.ts
Labels: refactoring

#51 [#50] : 로그인/회원가입 리팩토링
  package-lock.json
  src/Components/auth/AuthTestLoginBtn.tsx
  src/Components/auth/EmployeeCompanyForm.tsx
  src/Components/auth/LoginForm.tsx
  src/Components/auth/PersonalInfoForm.tsx
  src/Components/ui/card.tsx
  src/Components/ui/input.tsx
  src/Page/LoginPage.tsx
  src/Page/SignupPage.tsx
  src/api/auth/index.ts
  src/firebase/index.js
  src/hooks/useLogin.ts
  src/hooks/useSignup.ts
  src/model/index.ts
Labels: refactoring, style

#54 [#53] 로그인/회원가입 핫픽스
  src/Components/auth/EmployeeCompanyForm.tsx
  src/Components/auth/PersonalInfoForm.tsx
  src/Page/signupProcessPage/EmployeeFirstPage.jsx
  src/hooks/useLogin.ts
  src/hooks/useSignup.ts
  src/model/index.ts
Labels: hotFix

#57 [#56] zustand + shadcn 다크모드 구현
  src/App.jsx
  src/Components/MainContent.tsx
  src/Components/provider/ThemeProvider.tsx
  src/store/darkmode.store.ts
  tailwind.config.js
Labels: refactoring, style

#59 [#55] : 직원 처음 가입페이지 ui 구성 및 고용형태 추가, 급여부분 삭제
  package-lock.json
  package.json
  src/Components/GuidePopover.jsx
  src/Components/auth/EmployeeCompanyForm.tsx
  src/Components/auth/UserInfoTable.tsx
  src/Components/common/TooltipContainer.tsx
  src/Components/ui/progress.tsx
  src/Components/ui/select.tsx
  src/Components/ui/stepper.tsx
  src/Components/ui/table.tsx
  src/Components/ui/tooltip.tsx
  src/Page/LoginPage.tsx
  src/Page/SignupPage.tsx
  src/Page/signupProcessPage/EmployeeFirstPage.jsx
  src/Page/signupProcessPage/EmployeeFirstPage.tsx
  src/api/index.js
  src/hooks/useSignup.ts
  src/model/index.ts
  src/store/user.store.ts
Labels: refactoring, feat

#61 [#58] : MenuBar 컴포넌트 MUI->shadcn 라이브러리 변경 및 리팩토링
  package-lock.json
  package.json
  src/Components/MainContent.tsx
  src/Components/MenuBar.jsx
  src/Components/MenuBar/AdminMenuDesktop.tsx
  src/Components/MenuBar/AdminMenuMobile.tsx
  src/Components/MenuBar/EmployeeMenuBar.tsx
  src/Components/MenuBar/MenuBar.tsx
  src/Components/common/Header.jsx
  src/Components/provider/ThemeProvider.tsx
  src/Components/ui/button.tsx
  src/Components/ui/drawer.tsx
  src/constant/menuButton.ts
  src/constant/menuConfig.ts
  src/hooks/menu/useMenuActions.ts
  src/hooks/menu/useMenuBar.ts
  src/hooks/menu/useMenuItems.ts
  src/hooks/menu/useMenuState.ts
  src/hooks/menu/useWindowWidth.ts
  src/model/index.ts
  src/util/menuButtonStyle.ts
  src/util/menuUtils.ts
Labels: refactoring, style

#71 [#70] : 직원 페이지 최대너비 설정 및 메뉴바 다크모드 부분 오류 수정, 라우팅 방법 변경
  .prettierrc
  package-lock.json
  package.json
  src/Components/auth/AuthTestLoginBtn.tsx
  src/Components/common/Header.jsx
  src/Components/common/MainContent.tsx
  src/Components/common/menubar/EmployeeMenuBar.tsx
  src/Components/common/menubar/MenuBar.tsx
  src/Components/common/modal/WorkPlaceModal.tsx
  src/Components/common/provider/ThemeProvider.tsx
  src/Components/company/ ManagerRoutes.tsx
  src/Components/company/ManagerMainContent.tsx
  src/Components/company/company-settings/EmployeeInviteStep.tsx
  src/Components/company/company-settings/basic-setting/CompanyBasicStep.tsx
  src/Components/company/company-settings/job-setting/CompanyJobListStep.tsx
  src/Components/company/company-settings/night-holiday-setting/CompanyNightHolidayStep.tsx
  src/Components/company/company-settings/night-holiday-setting/HolidaySettings.tsx
  src/Components/company/company-settings/workplace-setting/map/WorkPlaceMap.tsx
  src/Components/container/EmployeePageContainer.tsx
  src/Components/container/ManagerPageContainer.tsx
  src/Components/employee/EmployeeMainContent.tsx
  src/Components/employee/EmployeeRoutes.tsx
  src/constants/routes.ts
  src/pages/common/CompanyMain.jsx
  src/pages/common/MainPage.jsx
  src/pages/manager/DateCheckPage.jsx
  src/store/user.store.ts
Labels: refactoring, feat, hotFix, style

#72 [#69] : useSelector 제거 후 darkModeStore 변경 (상태 변경 redux->zustand)
  src/Components/common/Footer.jsx
  src/Components/common/Footer.tsx
  src/Components/common/GuidePopover.tsx
  src/Components/common/calendar/MyDatePicker.tsx
  src/Components/common/modal/WorkPlaceModal.tsx
  src/Components/company/EmployeeItem.tsx
  src/pages/employee/AppGuidePage.tsx
  src/pages/manager/DateCheckPage.tsx
  src/pages/manager/EmployeeListPage.tsx
  src/pages/manager/ManagerSettingBasicPage.tsx
  src/pages/manager/ManagerSettingPage.tsx
  src/util/SalaryDay.util.js
Labels: refactoring

#74 [#73] : 관리자 페이지 메뉴바 구조 변경
  package-lock.json
  src/Components/common/menubar/AdminMenuDesktop.tsx
  src/Components/common/modal/WorkPlaceModal.tsx
  src/Components/company/ ManagerRoutes.tsx
  src/Components/container/ManagerPageContainer.tsx
  src/Components/employee/EmployeeMainContent.tsx
  src/Components/ui/sheet.tsx
  src/Components/ui/sidebar.tsx
  src/constants/routes.ts
  src/hooks/use-mobile.tsx
  src/index.css
  src/pages/manager/EmployeeManagePage.tsx
  src/pages/manager/PeriodAttendancePage.tsx
  src/pages/manager/PositionManagePage.tsx
  src/pages/manager/TodayAttenancePage.tsx
  src/pages/manager/VacationApprovedPage.tsx
  src/pages/manager/VacationListPage.tsx
  src/pages/manager/VacationRegisterPage.tsx
  src/pages/manager/WorkplaceManagePage.tsx
  tailwind.config.js
Labels: style

#76 [#73] : pr 코멘트 수정 작업
  src/Components/common/menubar/AdminMenuDesktop.tsx
  src/Components/company/ ManagerRoutes.tsx
  src/constants/routes.ts
  src/pages/manager/NoticePage.tsx
  src/pages/manager/VacationDetailPage.tsx
  src/pages/manager/VacationStatisticPage.tsx
Labels: refactoring

#78 [#75] : header 레이아웃 구성 및 sidebar trigger 추가
  src/App.tsx
  src/Components/common/Header.jsx
  src/Components/common/menubar/AdminMenuDesktop.tsx
  src/Components/company/ManagerMainContent.tsx
  src/Components/container/ManagerPageContainer.tsx
  src/Components/ui/sidebar.tsx
  src/layout/ManagerLayout.tsx
  src/pages/manager/ManagerSettingBasicPage.tsx
  tailwind.config.js
Labels: feat
