Repository kwonsuhyuk/OnAndOff, pull requests merged in 2025-04, with the labels that each got.

#143 [#142] : 직원 화면 홈, 메뉴 화면 ui 기본 작업 (더미데이터있음)
  package-lock.json
  package.json
  src/Components/common/CompanyInfo.tsx
  src/Components/common/CompanySummaryInfo.tsx
  src/Components/common/Header.tsx
  src/Components/common/PoweredByFooter.tsx
  src/Components/common/menubar/EmployeeMenuBar.tsx
  src/Components/common/menubar/ManagerMenuBar.tsx
  src/Components/common/menubar/MenuBar.tsx
  src/Components/company/ ManagerRoutes.tsx
  src/Components/employee/EmployeeEtcPageTitle.tsx
  src/Components/employee/EmployeeMainContent.tsx
  src/Components/employee/EmployeeRoutes.tsx
  src/Components/employee/mainpageBox/CommuteBox.tsx
  src/Components/employee/mainpageBox/CommuteHistoryBox.tsx
  src/Components/employee/mainpageBox/IntroGuideBox.tsx
  src/Components/employee/mainpageBox/NoticeBox.tsx
  src/Components/employee/mainpageBox/VacationBox.tsx
  src/Components/ui/accordion.tsx
  src/assets/aboutImg/mintaek.png
  src/constants/routes.ts
  src/layout/EmployeeLayout.tsx
  src/pages/common/AboutPage.tsx
  src/pages/employee/AppGuidePage.tsx
  src/pages/employee/EmployeeMenuPage.tsx
  src/pages/employee/MyVacationPage.tsx
  src/pages/manager/NoticePage.tsx
  tailwind.config.js
Labels: refactoring, feat, style

#147 [#146] : 직원 휴가 페이지 상세 ui (더미데이터 있음)
  src/Components/common/modal/EmployeeVacationDetailModal.tsx
  src/Components/company/vacation/EmployeeVacationItem.tsx
  src/Components/company/vacation/EmployeeVacationList.tsx
  src/Components/employee/EmployeeEtcPageTitle.tsx
  src/Components/employee/mainpageBox/VacationBox.tsx
  src/pages/employee/MyVacationPage.tsx
  tailwind.config.js
Labels: style

#149 [#148] : 직원 휴가 페이지 api 연동 후, UI 추가 수정, 리팩토링
  src/Components/Error.tsx
  src/Components/common/modal/EmployeeVacationDetailModal.tsx
  src/Components/employee/EmployeeMainContent.tsx
  src/Components/employee/mainpageBox/VacationBox.tsx
  src/Components/employee/vacation/EmployeeVacationItem.tsx
  src/Components/employee/vacation/EmployeeVacationList.tsx
  src/Components/employee/vacation/EmployeeVacationListSection.tsx
  src/Components/employee/vacation/EmployeeVacationTableFilterButton.tsx
  src/Components/employee/vacation/EmployeeVacationYearFilter.tsx
  src/constants/ vacation.ts
  src/constants/pagination.ts
  src/hooks/employee/useMyVacation.ts
  src/hooks/vacation/useFilteredVacationRequests.ts
  src/hooks/vacation/useGetEmployeeVacationList.ts
  src/pages/employee/MyVacationPage.tsx
  src/util/vacation.util.ts
Labels: refactoring, feat, style

#153 [#152] : 직원 출퇴근 기록 페이지 UI
  src/Components/common/calendar/MyCalendar.css
  src/Components/common/calendar/MyCalendar.jsx
  src/Components/common/calendar/MyCalendar.tsx
  src/Components/ui/calendar.tsx
  src/index.css
  src/pages/employee/ShowCalendarPage.jsx
  src/pages/employee/ShowCalendarPage.tsx
  src/reset.css
  tailwind.config.js
Labels: feat, style

#158 [#156] : 로딩스피너로 인한 직원페이지 ui 깨짐 오류 해결 및 다크모드 스위치 개선
  src/App.css
  src/App.tsx
  src/Components/common/Header.tsx
  src/Components/common/Loading.jsx
  src/Components/common/Loading.tsx
  src/Components/common/calendar/MyDatePicker.css
  src/Components/common/calendar/MyDatePicker.tsx
  src/Components/company/vacation/EmployeeVacationList.tsx
  src/Components/employee/EmployeeEtcPageTitle.tsx
  src/Components/employee/EmployeeRoutes.tsx
  src/Components/employee/mainpageBox/VacationBox.tsx
  src/Components/employee/showSalary/ SalaryInfoCard.jsx
  src/Components/employee/showSalary/ShowSalary.jsx
  src/Components/employee/vacation/EmployeeVacationList.tsx
  src/Components/employee/vacation/EmployeeVacationListSection.tsx
  src/Components/ui/switch.tsx
  src/constants/menuConfig.tsx
  src/constants/routes.ts
  src/layout/EmployeeLayout.tsx
  src/pages/common/AboutPage.tsx
  src/pages/employee/AppGuidePage.tsx
  src/pages/employee/EmployeeMenuPage.tsx
  src/pages/manager/NoticePage.tsx
Labels: hotFix, style

#157 [#154] : 관리자 기간 출퇴근 페이지 초기 UI (리팩x)
  src/Components/company/ ManagerRoutes.tsx
  src/Components/company/attendance/CustomCalendarHeader.tsx
  src/Components/company/attendance/PeriodAttCalendarDayCard.tsx
  src/Components/company/attendance/PeriodAttCalendarGrid.tsx
  src/Components/company/attendance/PeriodAttFilterSection.tsx
  src/Components/company/attendance/PeriodAttTable.tsx
  src/Components/container/manager/AttendancePageContainer.tsx
  src/constants/menuConfig.tsx
  src/constants/routes.ts
  src/pages/employee/EmployeeMenuPage.tsx
  src/pages/employee/MyVacationPage.tsx
  src/pages/employee/ShowCalendarPage.tsx
  src/pages/manager/CompanyInfoPage.tsx
  src/pages/manager/DateCheckPage.tsx
  src/pages/manager/EmployeeListPage.tsx
  src/pages/manager/HolidayNightManagePage.tsx
  src/pages/manager/NoticePage.tsx
  src/pages/manager/PeriodAttendancePage.tsx
  src/pages/manager/PositionManagePage.tsx
  src/pages/manager/TodayAttenancePage.tsx
  src/pages/manager/VacationDetailPage.tsx
  src/pages/manager/VacationStatisticPage.tsx
  src/pages/manager/WorkplaceManagePage.tsx
Labels: feat, style

#162 [#159] : 출퇴근 로직, 외근 로직 구현 (UI 및 코드 스플리팅 필요)
  src/Components/common/modal/CommuteConfirmModal.tsx
  src/Components/common/modal/OutWorkingModal.tsx
  src/Components/company/company-settings/workplace-setting/map/NaverMap.tsx
  src/Components/company/company-settings/workplace-setting/map/WorkPlaceMap.tsx
  src/Components/employee/EmployeeRoutes.tsx
  src/Components/employee/mainpageBox/CommuteBox.tsx
  src/Components/ui/textarea.tsx
  src/api/commute.api.ts
  src/api/index.ts
  src/constants/api.path.ts
  src/constants/distance.ts
  src/constants/menuConfig.tsx
  src/constants/routes.ts
  src/hooks/employee/useCommuteStatus.ts
  src/hooks/employee/useOutWorkingModal.ts
  src/hooks/employee/useWorkingModal.ts
  src/model/types/commute.type.ts
  src/pages/common/MainPage.tsx
  src/pages/employee/CommutePage.tsx
  src/pages/manager/DateCheckPage.tsx
  src/util/formatTime.util.js
  src/util/latlng.util.ts
  src/util/time.util.ts
Labels: feat

#167 [#164] : 전체/직원 근태 데이터 및 회사 공휴일 데이터 연동
  src/Components/common/AutoCompleteInput.tsx
  src/Components/common/calendar/MyCalendar.tsx
  src/Components/common/modal/ShowCalendarDetailModal.tsx
  src/Components/company/attendance/PeriodAttCalendarDayCard.tsx
  src/Components/company/attendance/PeriodAttCalendarGrid.tsx
  src/Components/company/attendance/PeriodAttCalendarList.tsx
  src/Components/company/attendance/PeriodAttFilterSection.tsx
  src/Components/ui/switch.tsx
  src/api/commute.api.ts
  src/constants/distance.ts
  src/hooks/employee/useShowCalendar.ts
  src/hooks/manager/usePeriodAttendance.ts
  src/model/types/commute.type.ts
  src/pages/employee/ShowCalendarPage.tsx
  src/util/commute.util.ts
  src/util/date.util.ts
  src/util/mapCommuteDataToCalendar.util.ts
  src/util/vacation.util.ts
Labels: feat, etc, style

#169 [#168] : 직원 홈페이지 이번주 출퇴근 현황 데이터 연동 및 UI 수정
  src/Components/employee/mainpageBox/CommuteHistoryBox.tsx
Labels: feat, style

#171 [#170] : 휴가 승인 된 데이터가 근태 현황에 업데이트되지 않는 현상 수정
  src/hooks/manager/useVacationRequests.ts
  src/hooks/vacation/useGetEmployeeVacationList.ts
  src/model/types/vacation.type.ts
Labels: hotFix

#172 166/daliycommute UI
  package-lock.json
  package.json
  src/Components/common/modal/VacationChartModal.tsx
  src/Components/company/attendance/DaliyAttendanceUI.tsx
  src/Components/ui/DatePicker.tsx
  src/Components/ui/carousel.tsx
  src/pages/manager/TodayAttenancePage.tsx
Labels: style
