Repository kwonsuhyuk/OnAndOff, pull requests merged in 2025-01, with the labels that each got.

#2 ♻️Refactor:리드미 파일 공백 추가(테스트용)
  README.md
Labels: bug

#4 [#3] : prettier 파일 생성
  .prettierrc
Labels: bug

#9 [#8] steps 상수 파일로 따로 분리해서 관리
  src/Components/Calendar/MyDatePicker.jsx
  src/Components/MenuBar.jsx
  src/Components/QR/QrScan.jsx
  src/Components/ShowSalary/ShowSalary.jsx
  src/Page/AppGuidePage.jsx
  src/Page/DateCheckPage.jsx
  src/Page/EmployeeListPage.jsx
  src/Page/ManagerSettingPage.jsx
  src/Page/ShowCalendarPage.jsx
  src/Page/signupProcessPage/EmployeeFirstPage.jsx
  src/constant/tourStep.js
Labels: refactoring

#11 ✨Feat: ts 사용위한 패키지 설치 및 설정
  package-lock.json
  package.json
  src/Page/AboutPage.tsx
  src/custom.d.ts
  tsconfig.json
  vite.config.js
Labels: feat
