Repository kwonsuhyuk/OnAndOff, pull requests merged in 2025-06, with the labels that each got.

#251 [#248] : 관리자/직원 페이지 joyride 최적화
  src/Components/common/TourController.tsx
  src/Components/common/modal/NoticeModal.tsx
  src/Components/company/attendance/DaliyAttendanceUI.tsx
  src/Components/company/attendance/PeriodAttCalendarGrid.tsx
  src/Components/company/attendance/PeriodAttFilterSection.tsx
  src/Components/company/attendance/Settlement.tsx
  src/Components/company/table/VacationTabContent.tsx
  src/Components/employee/vacation/EmployeeVacationListSection.tsx
  src/Components/ui/DatePicker.tsx
  src/constants/managerTourSteps.ts
  src/layout/ManagerLayout.tsx
  src/pages/manager/EmployeeListPage.tsx
  src/pages/manager/NoticePage.tsx
  src/pages/manager/PeriodAttendancePage.tsx
  src/pages/manager/VacationDetailPage.tsx
Labels: QA

#257 [#252] : joyride, store 관련 추가 수정
  src/Components/common/Header.tsx
  src/Components/common/TourController.tsx
  src/Components/ui/skeleton.tsx
  src/hooks/use-tour.ts
  src/layout/ManagerLayout.tsx
  src/store/darkmode.store.ts
  src/store/darkmodeSlice.js
  src/store/userSlice.js
  src/util/tourStorage.util.ts
Labels: QA

#266 [#263] : text hotfix
  public/images/mobile-attendance.png
  public/images/period-attendance.png
  public/images/settlement.png
  public/images/today-attendance.png
  public/images/vacation-detail.png
  public/images/vacation-statistic.png
  src/Components/common/menubar/ManagerMenuBar.tsx
  src/Components/common/modal/NoticeModal.tsx
  src/Components/common/modal/ShowCalendarDetailModal.tsx
  src/Components/common/modal/commonModalLayout/RegisterModal.tsx
  src/constants/managerTourSteps.ts
  src/hooks/employee/useShowCalendar.ts
  src/hooks/manager/useVacationRegisterModal.ts
  src/hooks/manager/useVacationRequests.ts
  src/model/types/vacation.type.ts
  src/pages/common/IndexPage.tsx
  src/pages/employee/EmployeeMenuPage.tsx
  src/pages/manager/NoticePage.tsx
Labels: hotFix

#271 [#268] : created at vacation
  src/Components/company/attendance/PeriodAttCalendarDayCard.tsx
  src/Components/company/attendance/PeriodAttCalendarGrid.tsx
  src/hooks/manager/useVacationRequests.ts
Labels: hotFix

#270 [#269] : 정산 QA 관련
  .firebase/hosting.ZGlzdA.cache
  bundle-report.html
  src/Components/common/modal/NoticeModal.tsx
  src/Components/company/attendance/Settlement.tsx
  src/Components/company/vacation/VacationChart.tsx
  src/hooks/manager/useSettlement.ts
  src/hooks/vacation/useVacationChartData.ts
Labels: QA

#273 [#272] : 외근 요청 기능 및 금일 출퇴근 디자인 수정, 관련 안내 페이지 구현
  public/images/guide/admin-outwork-confirmed.png
  public/images/guide/admin-outwork-modal.png
  public/images/guide/checkedin.png
  public/images/guide/checkin.png
  public/images/guide/commute-modal.png
  public/images/guide/commute.png
  public/images/guide/complete.png
  public/images/guide/location.jpeg
  public/images/guide/outworking-button.png
  public/images/guide/outworking-complete.png
  public/images/guide/outworking-modal.png
  public/images/guide/outworking-request-admin.png
  public/images/guide/outworking-request.png
  public/images/금일출퇴근.png
  public/images/기간출퇴근.png
  public/images/정산.png
  public/images/출근하기.png
  public/images/휴가내역.png
  public/images/휴가통계.png
  src/Components/common/modal/CommuteConfirmModal.tsx
  src/Components/common/modal/OutWorkingModal.tsx
  src/Components/common/modal/OutworkRequestModal.tsx
  src/Components/common/modal/VacationRequestModal.tsx
  src/Components/common/modal/WorkplaceDetailModal.tsx
  src/Components/company/GlobalOutworkAlert.tsx
  src/Components/company/ManagerHomeBoxLayout.tsx
  src/Components/company/ManagerMainContent.tsx
  src/Components/company/RequestAlarmButton.tsx
  src/Components/company/TodayCommuteBox.tsx
  src/Components/company/attendance/DaliyAttendanceUI.tsx
  src/Components/employee/mainpageBox/CommuteBox.tsx
  src/Components/employee/mainpageBox/CommuteBoxRenderItem.tsx
  src/Components/employee/mainpageBox/IntroGuideBox.tsx
  src/Components/ui/notificationDropdown.tsx
  src/api/commute.api.ts
  src/api/index.ts
  src/constants/api.path.ts
  src/constants/menuConfig.tsx
  src/hooks/employee/useCommuteBox.ts
  src/hooks/employee/useCommuteStatus.ts
  src/hooks/employee/useMyOutworkRequests.ts
  src/hooks/employee/useOutWorkingModal.ts
  src/hooks/manager/useFilterWork.ts
  src/hooks/manager/useOutworkRequests.ts
  src/hooks/manager/useTodayCommuteData.ts
  src/layout/ManagerLayout.tsx
  src/model/types/commute.type.ts
  src/model/types/notification.type.ts
  src/pages/CommuteGuidePage.tsx
  src/pages/OutworkGuidePage.tsx
  src/routes/MainRoutes.tsx
  src/stories/CommuteBoxRenderItem.stories.tsx
  src/util/commute.util.ts
Labels: feat, style, QA

#276 [#275] : joyride 추가 수정 (외근 요청) 및 직원페이지 달력 범례 수정
  src/Components/company/EmployeeListBox.tsx
  src/Components/company/ManagerVacationBox.tsx
  src/Components/company/TodayCommuteBox.tsx
  src/Components/company/WorkplaceBox.tsx
  src/Components/company/attendance/DaliyAttendanceUI.tsx
  src/constants/managerTourSteps.ts
  src/pages/manager/NoticePage.tsx
  src/util/commute.util.ts
Labels: hotFix

#286 [#285] : 게스트 로그인 계정 변경
  src/Components/auth/AuthTestLoginBtn.tsx
Labels: hotFix

#288 [#287] : 로그인/회원가입 페이지 폼 문구 추가
  src/Components/auth/EmployeeCompanyForm.tsx
  src/Components/auth/LoginForm.tsx
  src/Components/auth/PersonalInfoForm.tsx
Labels: hotFix

#295 [#294] : download guide
  .gitignore
  src/Components/common/CompanySummaryInfo.tsx
  src/Components/employee/EmployeeRoutes.tsx
  src/assets/guideImg/androidguide.jpeg
  src/assets/guideImg/androidguide2.jpeg
  src/assets/guideImg/iphoneguide.jpeg
  src/assets/guideImg/iphoneguide2.jpeg
  src/constants/menuConfig.tsx
  src/pages/AppGuidePage.tsx
  src/pages/employee/AppGuidePage.tsx
  src/routes/MainRoutes.tsx
Labels: QA

#306 [#305] : feedback qa
  .firebase/hosting.ZGlzdA.cache
  bundle-report.html
  src/Components/common/menubar/ManagerMenuBar.tsx
  src/Components/common/modal/VacationChartModal.tsx
  src/Components/common/modal/VacationRegisterModal.tsx
  src/Components/company/vacation/VacationChart.tsx
  src/Components/company/vacation/VacationPieChart.tsx
  src/Components/employee/EmployeeRoutes.tsx
  src/Components/employee/mainpageBox/IntroGuideBox.tsx
  src/Components/employee/vacation/EmployeeVacationYearFilter.tsx
  src/Components/ui/date-range-picker.tsx
  src/constants/ vacation.ts
  src/constants/chartColor.ts
  src/constants/devnotes.ts
  src/constants/dummyEmployees.ts
  src/constants/dummyVacationRequests.ts
  src/constants/menuConfig.tsx
  src/constants/vacationSelect.ts
  src/constants/vacationstatisticColumns.ts
  src/hooks/manager/useVacationDetailModal.ts
  src/hooks/vacation/useVacationChartData.ts
  src/hooks/vacation/useVacationPieChart.ts
  src/hooks/vacation/useVacationStatisticTableData.ts
  src/model/types/vacation.type.ts
  src/pages/common/UpdateNodePage.tsx
  src/routes/MainRoutes.tsx
  src/util/vacation.util.ts
Labels: feat, QA
