Repository kwonsuhyuk/OnAndOff, pull requests merged in 2025-05, with the labels that each got.

#180 [#179] : 관리자 근무지 범위 설정 기능
  package-lock.json
  src/Components/common/modal/WorkPlaceModal.tsx
  src/Components/company/company-settings/workplace-setting/WorkPlaceItem.tsx
  src/Components/company/company-settings/workplace-setting/map/NaverMap.tsx
  src/Components/company/company-settings/workplace-setting/map/WorkPlaceMap.tsx
  src/model/types/company.type.ts
  src/pages/manager/TodayAttenancePage.tsx
Labels: refactoring, feat

#186 [#185]: Loading UI
  src/Components/common/Loading.tsx
Labels: style

#188 [#187] : auth qa
  src/Components/common/CompanySummaryInfo.tsx
  src/Components/common/PopoverHint.tsx
  src/Components/company/company-settings/EmployeeInviteStep.tsx
  src/Components/employee/EmployeeJobSelection.tsx
  src/Components/employee/EmployeementTypeSelection.tsx
  src/hooks/auth/useSettingEmployee.ts
  src/pages/auth/signupProcessPage/EmployeeFirstPage.tsx
Labels: QA

#195 [#194] : chart, 금일 출퇴근 관련 QA
  src/Components/common/chart/CustomLegend.tsx
  src/Components/common/chart/CustomTooltip.tsx
  src/Components/common/modal/VacationChartModal.tsx
  src/Components/company/EmployeeListBox.tsx
  src/Components/company/attendance/DaliyAttendanceUI.tsx
  src/Components/company/vacation/VacationChart.tsx
  src/Components/company/vacation/VacationFilter.tsx
  src/Components/company/vacation/VacationPieChart.tsx
  src/Components/ui/carousel.tsx
  src/constants/chartColor.ts
  src/hooks/vacation/useVacationPieChart.ts
Labels: QA

#193 [#190] : employee commute qa
  src/Components/common/modal/CommuteConfirmModal.tsx
  src/Components/common/modal/OutWorkingModal.tsx
  src/Components/employee/mainpageBox/CommuteBoxRenderItem.tsx
  src/Components/employee/mainpageBox/CommuteHistoryBox.tsx
  src/Components/employee/mainpageBox/CommutePageUI.tsx
  src/hooks/employee/useNearbyWorkplaces.ts
  src/pages/employee/CommutePage.tsx
Labels: QA

#191 [#189] : notice qa
  package-lock.json
  src/Components/common/modal/NoticeModal.tsx
  src/Components/company/notice/NoticeCard.tsx
  src/api/notice.api.ts
  src/hooks/manager/useNotice.ts
  src/model/types/manager.type.ts
  src/pages/manager/NoticePage.tsx
Labels: QA

#197 [#192] : workplace qa
  src/Components/common/modal/WorkPlaceModal.tsx
  src/Components/company/company-settings/workplace-setting/CompanyWorkPlaceStep.tsx
  src/Components/company/company-settings/workplace-setting/WorkPlaceItem.tsx
  src/Components/company/company-settings/workplace-setting/WorkPlaceList.tsx
Labels: QA

#201 [#200] : vacation qa
  src/Components/common/AutoCompleteInput.tsx
  src/Components/common/modal/VacationDetailModal.tsx
  src/Components/common/modal/VacationRegisterModal.tsx
  src/Components/ui/data-table.tsx
  src/Components/ui/date-range-picker.tsx
  src/hooks/manager/useVacationDetailModal.ts
  src/pages/manager/VacationDetailPage.tsx
Labels: QA

#206 [#198] use blocker
  package-lock.json
  package.json
  src/App.tsx
  src/Components/common/menubar/EmployeeMenuBar.tsx
  src/Components/common/menubar/ManagerMenuBar.tsx
  src/Components/common/menubar/MenuBar.tsx
  src/Components/company/ ManagerRoutes.tsx
  src/Components/company/EmployeeListBox.tsx
  src/Components/employee/EmployeeRoutes.tsx
  src/constants/menuConfig.tsx
  src/hooks/auth/useSettingEmployee.ts
  src/hooks/company-settings/useFormBlocker.ts
  src/hooks/company-settings/useSubmitCompanyData.ts
  src/hooks/manager/usePeriodAttendance.ts
  src/layout/AuthenticatedLayout.tsx
  src/layout/ManagerLayout.tsx
  src/layout/NotLoginLayout.tsx
  src/layout/RootLayout.tsx
  src/main.tsx
  src/pages/ErrorPage.tsx
  src/pages/common/Notfound.jsx
  src/pages/common/Notfound.tsx
  src/pages/manager/CompanyInfoPage.tsx
  src/pages/manager/HolidayNightManagePage.tsx
  src/pages/manager/PositionManagePage.tsx
  src/pages/manager/WorkplaceManagePage.tsx
  src/routes/MainRoutes.tsx
Labels: QA

#209 [#208] : 수동출퇴근 QA, 로그인 페이지 보이는 버그 수정
  src/App.tsx
  src/Components/common/ScrollToTop.tsx
  src/Components/common/modal/SelfCommuteModal.tsx
  src/Components/company/ManagerHomeBoxLayout.tsx
  src/Components/company/TodayCommuteBox.tsx
  src/Components/company/WorkplaceBox.tsx
  src/Components/company/attendance/DaliyAttendanceUI.tsx
  src/Components/ui/DatePicker.tsx
  src/hooks/employee/useCommuteModal.ts
  src/layout/NotLoginLayout.tsx
  src/layout/RootLayout.tsx
Labels: feat, QA

#210 [#207] : myvacation qa
  package-lock.json
  src/Components/Seo.tsx
  src/Components/common/modal/EmployeeVacationDetailModal.tsx
  src/Components/common/modal/VacationRequestModal.tsx
  src/Components/employee/vacation/EmployeeVacationTableFilterButton.tsx
  src/Components/employee/vacation/EmployeeVacationYearFilter.tsx
  src/hooks/vacation/useGetEmployeeVacationList.ts
  src/layout/NotLoginLayout.tsx
  src/main.tsx
  src/pages/employee/MyVacationPage.tsx
Labels: QA

#214 [#213] : interactive guide setting
  package-lock.json
  package.json
  src/Components/common/AppTitle.tsx
  src/Components/common/CompanySummaryInfo.tsx
  src/Components/common/Header.tsx
  src/Components/common/menubar/ManagerMenuBar.tsx
  src/Components/ui/sidebar.tsx
  src/layout/EmployeeLayout.tsx
  src/layout/ManagerLayout.tsx
  src/layout/RootLayout.tsx
  src/pages/employee/EmployeeMenuPage.tsx
Labels: feat

#216 [#215]: manifest , favicon 수정
  index.html
  manifest.json
  public/favicon/android-chrome-192x192.png
  public/favicon/android-chrome-512x512.png
  public/favicon/apple-touch-icon.png
  public/favicon/favicon-16x16.png
  public/favicon/favicon-32x32.png
  public/favicon/favicon.ico
Labels: etc

#218 [#217] : guitar qa
  src/Components/common/Header.tsx
  src/Components/common/calendar/MyCalendar.tsx
  src/Components/common/modal/WorkPlaceModal.tsx
  src/Components/company/attendance/PeriodAttFilterSection.tsx
  src/Components/company/company-settings/workplace-setting/map/NaverMap.tsx
  src/Components/company/table/EmployeeModifyModal.tsx
  src/Components/employee/mainpageBox/CommuteBox.tsx
  src/pages/employee/CommutePage.tsx
  src/pages/manager/PeriodAttendancePage.tsx
Labels: QA

#220 [#219] : 공지사항 페이지 기능 투어 추가
  src/Components/common/TourController.tsx
  src/constants/managerTourSteps.ts
  src/hooks/use-tour.ts
  src/layout/ManagerLayout.tsx
  src/pages/manager/NoticePage.tsx
  src/store/tour.store.ts
  src/util/tourStorage.util.ts
Labels: feat

#222 [#221] : 관리자 처음 튜토리얼 박스 제공
  src/Components/company/BasicGuideStepBox.tsx
  src/Components/company/ManagerMainContent.tsx
  src/layout/NotLoginLayout.tsx
Labels: feat

#225 ✨Feat: 관리자 joyride 스크립트 작성
  src/Components/common/TourController.tsx
  src/Components/company/CompanyCodeCopy.tsx
  src/Components/company/EmployeeListBox.tsx
  src/Components/company/ManagerMainContent.tsx
  src/Components/company/ManagerVacationBox.tsx
  src/Components/company/TodayCommuteBox.tsx
  src/Components/company/WorkplaceBox.tsx
  src/Components/company/attendance/DaliyAttendanceUI.tsx
  src/Components/company/company-settings/basic-setting/CompanyBasicStep.tsx
  src/Components/company/company-settings/job-setting/CompanyJobListStep.tsx
  src/Components/company/company-settings/job-setting/JobListCard.tsx
  src/Components/company/company-settings/night-holiday-setting/HolidaySettings.tsx
  src/Components/company/company-settings/night-holiday-setting/NightPaySettings.tsx
  src/Components/company/company-settings/night-holiday-setting/PayCheckDaySelect.tsx
  src/Components/company/company-settings/workplace-setting/CompanyWorkPlaceStep.tsx
  src/Components/company/company-settings/workplace-setting/WorkPlaceList.tsx
  src/Components/company/vacation/VacationChart.tsx
  src/Components/company/vacation/VacationFilter.tsx
  src/Components/company/vacation/VacationPieChart.tsx
  src/Components/company/vacation/VacationStatisticTable.tsx
  src/Components/ui/DatePicker.tsx
  src/constants/managerTourSteps.ts
  src/pages/manager/CompanyInfoPage.tsx
  src/pages/manager/HolidayNightManagePage.tsx
  src/pages/manager/PositionManagePage.tsx
  src/pages/manager/TodayAttenancePage.tsx
  src/pages/manager/VacationStatisticPage.tsx
  src/pages/manager/WorkplaceManagePage.tsx
Labels: feat

#229 [#224] : manager joyride
  src/Components/common/TourController.tsx
  src/Components/company/attendance/PeriodAttCalendarGrid.tsx
  src/Components/company/attendance/PeriodAttFilterSection.tsx
  src/Components/company/notice/NoticeCard.tsx
  src/Components/company/table/EmployeeFilter.tsx
  src/Components/company/table/VacationTabContent.tsx
  src/Components/container/manager/VacationRequestPageContainer.tsx
  src/constants/managerTourSteps.ts
  src/pages/manager/EmployeeListPage.tsx
  src/pages/manager/NoticePage.tsx
  src/pages/manager/PeriodAttendancePage.tsx
  src/pages/manager/VacationDetailPage.tsx
Labels: feat

#232 [#230] : employee joyride (비제어)
  src/Components/common/CompanyInfo.tsx
  src/Components/common/Header.tsx
  src/Components/common/TourController.tsx
  src/Components/common/modal/NoticeModal.tsx
  src/Components/company/notice/NoticeCard.tsx
  src/Components/employee/EmployeeMainContent.tsx
  src/Components/employee/mainpageBox/CommuteBox.tsx
  src/Components/employee/mainpageBox/CommuteHistoryBox.tsx
  src/Components/employee/mainpageBox/NoticeBox.tsx
  src/Components/employee/mainpageBox/VacationBox.tsx
  src/Components/employee/vacation/EmployeeVacationYearFilter.tsx
  src/constants/employeeTourSteps.ts
  src/constants/managerTourSteps.ts
  src/hooks/company-settings/useWorkplacePage.ts
  src/hooks/employee/useNearbyWorkplaces.ts
  src/hooks/use-tour.ts
  src/layout/EmployeeLayout.tsx
  src/layout/ManagerLayout.tsx
  src/pages/employee/EmployeeMenuPage.tsx
  src/pages/employee/MyVacationPage.tsx
  src/pages/employee/ShowCalendarPage.tsx
  src/pages/manager/NoticePage.tsx
  src/store/tour.store.ts
Labels: feat

#240 [#234] : 직원 페이지 최종 QA (모달 관련 X)
  src/Components/common/CompanySummaryInfo.tsx
  src/Components/company/notice/NoticeCard.tsx
  src/Components/company/notice/NoticeDetailModal.tsx
  src/Components/employee/mainpageBox/VacationBox.tsx
  src/Components/employee/vacation/EmployeeVacationItem.tsx
  src/Components/ui/notificationDropdown.tsx
  src/pages/employee/ShowCalendarPage.tsx
  src/pages/manager/NoticePage.tsx
Labels: QA

#245 [#241] : pointcolor 교체 및 금일출퇴근 홈화면 , 리스트 , 차트색상 등 디자인 전체적으로 수정
  src/Components/common/CompanySummaryInfo.tsx
  src/Components/common/modal/VacationChartModal.tsx
  src/Components/common/modal/WorkplaceDetailModal.tsx
  src/Components/common/modal/commonModalLayout/DetailModal.tsx
  src/Components/company/ SummaryCard.tsx
  src/Components/company/BasicGuideStepBox.tsx
  src/Components/company/EmployeeListBox.tsx
  src/Components/company/ManagerHomeBoxLayout.tsx
  src/Components/company/ManagerVacationBox.tsx
  src/Components/company/TodayCommuteBox.tsx
  src/Components/company/WorkplaceBox.tsx
  src/Components/company/attendance/DaliyAttendanceUI.tsx
  src/Components/company/company-settings/job-setting/JobCard.tsx
  src/Components/company/company-settings/job-setting/JobListCard.tsx
  src/Components/company/company-settings/workplace-setting/WorkPlaceItem.tsx
  src/Components/company/company-settings/workplace-setting/WorkPlaceList.tsx
  src/Components/company/vacation/VacationChart.tsx
  src/constants/chartColor.ts
  src/hooks/company-settings/useCompanyJobListForm.ts
  src/hooks/company-settings/useCompanyWorkPlacesListForm.ts
  src/hooks/vacation/useVacationPieChart.ts
  src/pages/common/IndexPage.tsx
  src/pages/manager/WorkplaceManagePage.tsx
  tailwind.config.js
Labels: style, QA
